---
- name: "Install Tmux"
  apt:
    name: tmux
    state: present
  become: true
  become_method: sudo
- name: "Cloning Tmux Config"
  git:
    repo: "https://github.com/gpakosz/.tmux.git"
    dest: "{{ ansible_env.HOME }}/.tmux"


